### ISSUE TITLE
Add extended syntax support for model handles

### ISSUE THREAD

**Issue by shuttie** [nixiesearch/nixiesearch#253]
As for now it's just `namespace/name`. It would be great to also pass params like:
* model file if there are many models (regular thing for ONNX and GGUF models)
* should it be cached locally?
* pooling type for embedding models
* all the llamacpp params for inference

It should look like this for short handles:
```yaml
fields:
  title:
    type: text
    search:
      type: semantic
      model: ns/name
```

and long handle should look like this:

```yaml
fields:
  title:
    type: text
    search:
      type: semantic
      model: 
        hf:
          handle: ns/name
          file: model.onnx
          pooling: mean
          cache: false

```
