### ISSUE TITLE
Required field support

### ISSUE THREAD

**Issue by shuttie** [nixiesearch/nixiesearch#482]
So you can mark a field as mandatory, so all docs with no field will be rejected by the indexer. We see it as a part of the field schema like this:

```
schema:
  foo:
    fields:
      price:
        type: float
        required: true
```

It should not anyhow affect indexing or search, it's just  a matter of enforcing document schema during ingestion.
